### PR TITLE
chore: Create question popup

### PR DESCRIPTION
**Pull request by mhawryluk**
# Description

Create a popup for the quiz system. Can be tested by pressing 'Q'.
Not integrated with the game mechanics - just a popup giving the user ability to select the answer to a question and see the result.

Zrzut ekranu 2022-05-4 o 22 35 06
Zrzut ekranu 2022-05-4 o 22 35 16

# Checklist

* [x] Included code to test these changes -> kinda
* [x] Updated Jira

### CODE REVIEW

**Review by co012 — APPROVED** [review]
LGTM

**Comment by zamojtel** [comment]
Looks nice

**Review by zamojtel — COMMENTED** [review]
LGTM

**Review by zamojtel — APPROVED** [review]
LGTM

**Pull request merged**
